language: ruby
cache: bundler
branches:
  only:
    - master
script: 
  - wget https://raw.githubusercontent.com/CSIS-iLab/health-commission/master/algolia-sync.rb
  - chmod +x algolia-sync.rb
  - bundle install
  - bundle exec ruby algolia-sync.rb
rvm:
 - 2.5.1