title: "CSIS Commission on Strengthening America's Health Security"
email: csisideaslab@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Quick starter project for Jekyll including full setup for gulp, Sass, Autoprefixer, Bourbon/Neat/Bitters, Browserify, imagemin, Browsersync, PostCSS etc. Built on top of Frasco
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:

# Content types will be defined here
collections:
  posts:
    title: All Articles
    output: true
    permalink: "/:path/articles/"
  series:
    title: Series
    output: true
    permalink: "/:path/series/"
  themes:
    title: Themes
    output: true
    permalink: "/:path/themes/"
  events:
    title: Events
    output: true
    permalink: "/:path/events/"
  authors:
    title: Authors
    output: true
    permalink: "/:path/authors/"


# Default front matter values for a collection will be defined here
defaults:
- scope:
    path: ''
  values:
    image: # Default social media image should go here
- scope:
    path: ''
    type: 'posts'
  values:
    layout: post
    permalink: "/articles/:slug/"
- scope:
    path: ''
    type: 'series'
  values:
    layout: post
    permalink: "/series/:slug/"
- scope:
    path: ''
    type: 'themes'
  values:
    layout: post
    permalink: "/themes/:slug/"
- scope:
    path: ''
    type: 'events'
  values:
    layout: post
    permalink: "/events/:slug/"
- scope:
    path: ''
    type: 'authors'
  values:
    layout: post
    permalink: "/authors/:slug/"

cloudinary_url: https://res.cloudinary.com/csisideaslab/image/upload/

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - frasco.config.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - prettier.config.js
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
