title: "CSIS Commission on Strengthening America's Health Security"
email: csisideaslab@gmail.com
description: >-
  The CSIS Commission on Strengthening America’s Health Security aims to chart a bold vision for the future of U.S. leadership in global health security, at home and abroad. The Commission brings together a distinguished and diverse group of senior leaders who bridge the health and security fields, comprising members of Congress, past administrations, industry, foundations, universities, and NGOs, and the Commission is advised by a group of preeminent subject experts. This is a two-year effort organized by the CSIS Global Health Policy Center.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://healthsecurity.csis.org"

date_format: '%b %-d, %Y'
tag_url: /search/?dFR[keywords][0]=
theme_url: /search/?dFR[themes][0]=
content_type_url: /search/?dFR[content_type][0]=

# Content types will be defined here
collections:
  posts:
    title: All Articles
    output: true
    permalink: "/:path/articles/"
  series:
    title: Series
    output: true
    permalink: "/:path/series/"
  themes:
    title: Themes
    output: true
    permalink: "/:path/themes/"
  events:
    title: Events
    output: true
    permalink: "/:path/events/"
  authors:
    title: Authors
    output: true
    permalink: "/:path/authors/"


# Default front matter values for a collection will be defined here
defaults:
- scope:
    path: ''
    type: 'posts'
  values:
    layout: post
    show_page_highlights: true
    page_highlights_download: true
    page_highlights_cite: true
    page_highlights_share: true
    permalink: "/articles/:slug/"
- scope:
    path: ''
    type: 'series'
  values:
    layout: archive
    permalink: "/series/:slug/"
    use_algolia: true
    algolia_facet: series
- scope:
    path: ''
    type: 'themes'
  values:
    layout: themes
    show_page_highlights: true
    page_highlights_featured_post: true
    permalink: "/themes/:slug/"
- scope:
    path: ''
    type: 'events'
  values:
    layout: post
    show_page_highlights: true
    page_highlights_cite: true
    page_highlights_share: true
    permalink: "/events/:slug/"
- scope:
    path: ''
    type: 'authors'
  values:
    layout: archive
    permalink: "/authors/:slug/"
    use_algolia: true
    algolia_facet: authors


cloudinary_url: https://res.cloudinary.com/csisideaslab/image/upload/

twitter:
  card: summary
logo: /assets/images/health-commission-twitter.jpg

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
exclude:
  - frasco.config.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - prettier.config.js
  - README.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
