---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - posts
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - events
- type: directory
  path: _themes
  label: Themes
  create: all
  match: "**/*"
  templates:
  - themes
- type: directory
  path: _series
  label: Series
  create: all
  match: "**/*"
  templates:
  - series
- type: document
  path: _data/keywords.yml
  label: Tags
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - authors
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: DATA
- type: document
  path: _data/content_types.yml
  label: Content Types
- type: document
  path: _data/language.yml
  label: Language
- type: heading
  label: Members
- type: document
  path: _data/co_chairs.csv
  label: Co-Chairs
- type: document
  path: _data/members_contributors.csv
  label: Members and Contributors
  read_only: true
upload_dir: health-commission
public_path: https://res.cloudinary.com/csisideaslab/image/upload
front_matter_path: https://res.cloudinary.com/csisideaslab/image/upload
use_front_matter_path: true
file_template: ":filename:"
