---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - posts
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - events
- type: directory
  path: _themes
  label: Themes
  create: all
  match: "**/*"
  templates:
  - themes
- type: directory
  path: _series
  label: Series
  create: all
  match: "**/*"
  templates:
  - series
- type: document
  path: _data/keywords.yml
  label: Tags
- type: directory
  path: _authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - authors
- type: jekyll-pages
  label: Pages
  create: all
- type: heading
  label: DATA
- type: document
  path: _data/content_types.yml
  label: Content Types
- type: document
  path: _data/language.yml
  label: Language
- type: document
  path: _data/co_chairs.csv
  label: Co-Chairs
- type: document
  path: _data/main_menus.yml
  label: Main Menus
  read_only: true
upload_dir: health-commission
public_path: https://res.cloudinary.com/csisideaslab/image/upload
front_matter_path: https://res.cloudinary.com/csisideaslab/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
