---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: MANAGE
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - posts
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - events
- type: document
  path: index.md
  label: Homepage
- type: heading
  label: COMMISSION MEMBERRS
- type: directory
  path: _authors
  label: All Author Images and Byline text
  create: all
  match: "**/*"
  templates:
  - authors
- type: document
  path: _data/co_chairs.json
  label: Co-Chairs
- type: document
  path: _data/experts_advisors.json
  label: Experts & Advisors
- type: document
  path: _data/members_contributors.json
  label: Members & Contributors
- type: document
  path: _data/secretariat.json
  label: Secretariat
- type: heading
  label: DATA
- type: document
  path: _data/keywords.yml
  label: Tags
- type: document
  path: _data/content_types.yml
  label: Content Types
- type: document
  path: _data/language.yml
  label: Language
- type: document
  path: _data/main_menus.yml
  label: Main Menus
  read_only: true
- type: heading
  label: OTHER
- type: directory
  path: _themes
  label: Themes
  create: all
  match: "**/*"
  templates:
  - themes
- type: directory
  path: _series
  label: Series
  create: all
  match: "**/*"
  templates:
  - series
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: health-commission
public_path: https://res.cloudinary.com/csisideaslab/image/upload
front_matter_path: https://res.cloudinary.com/csisideaslab/image/upload
use_front_matter_path: true
file_template: ":filename:"
instant_preview: true
build:
  preview_command: npm run forestry:preview
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: npm run forestry:preview
